### ISSUE TITLE
Failed to compile JST

### ISSUE THREAD

**Issue by japboy** [techtribe/grunt-static-handlebars#2]
I made my own [small sample](https://github.com/japboy/grunt-handlebars-sample) to use `grunt-static-handlebars` but it doesn't work for me:

```
Running "staticHandlebars:source" (staticHandlebars) task
Warning: Cannot call method 'indexOf' of undefined Use --force to continue.

Aborted due to warnings.
```

Could someone please point me out what is wrong? Thanks in advance.

**Comment by techtribe** [comment]
Thanks for the example, but I did not (yet) anticipate that you don't use any helpers. I will change that, but for the time being, please add (like the example on the README.md file) the helpers-property and your example will work (I tested):

``` js
partials : ''<%= path.source %>/**/*.hbp'',
helpers : ""
```

FYI & with upcoming releases I will anticipate on ignoring partials or helpers properties.

**Comment by japboy** [comment]
@Techtribe thanks!

**Comment by japboy** [comment]
I added `helpers: ''` though I still get error:

```
Running "staticHandlebars:source" (staticHandlebars) task
Warning: must provide pattern Use --force to continue.

Aborted due to warnings.
```

What am I missing...?

**Comment by japboy** [comment]
I put empty `.js` file and that seems to avoid this issue:

```
helpers : '<%= path.source %>/js/empty.js'
```

**Comment by techtribe** [comment]
Thnx for the comment and apparantly I made it work inside the plugin and assumed that `helpers:''` would work. I am working on a new version which would fix these kind of issues. Hope to publish today/tomorrow.

FYI & sorry.

**Comment by techtribe** [comment]
Try using d06f9cb43f (v0.6.0) with your setup. Will fix the empty helper and if any issues, let me know.

**Comment by japboy** [comment]
v0.6.0 now works fine. Cheers :+1:
