### ISSUE TITLE
logError is broken

### ISSUE THREAD

**Issue by esromneb** [techtribe/grunt-static-handlebars#7]
I'm new to both node and grunt-static-handlebars but I'm pretty sure logError() shouldn't be hiding messages inside debug output stream.  I found this by rendering a template (bar.hbt) with invalid json inside bar.json.

This is the output I get:
`Warning: Cannot set property 'extends' of null Use --force to continue.`

The output I expect (only visible using grunt --debug):
`Your JSON file (./bar.json) has no valid syntax [SyntaxError: Unexpected token /]`

The error comes from context.js line 41.  Log error hides this output by appending to the grunt debug stream.  I think that logError should just print using grunt.log.write()

The error I'm seeing is happening on line 395 of static_handlebars.js because getContext() is returning null, and everything just keeps on moving after logError is called

**Comment by joeyvandijk** [comment]
Could you try with the new version (0.9.0), sorry I didn't responded earlier.

**Comment by afuhrtrumpet** [comment]
I am using the newest version (0.9.0), and this issue is still present with invalid JSON.

**Comment by OlivierCo** [comment]
This is due to invalide JSON, try to http://jsonlint.com/ first and try again.
